use counterexample;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `block`;
DROP TABLE IF EXISTS `blocks`;
DROP TABLE IF EXISTS `char_variable`;
DROP TABLE IF EXISTS `char_variables`;
DROP TABLE IF EXISTS `hibernate_sequence`;
DROP TABLE IF EXISTS `int_variable`;
DROP TABLE IF EXISTS `int_variables`;
DROP TABLE IF EXISTS `problem`;
DROP TABLE IF EXISTS `problems`;
DROP TABLE IF EXISTS `test_case`;
DROP TABLE IF EXISTS `test_result`;
DROP TABLE IF EXISTS `test_results`;
DROP TABLE IF EXISTS `testcases`;
DROP TABLE IF EXISTS `users`;
SET FOREIGN_KEY_CHECKS = 1;